### ISSUE TITLE
Kafka module not supported in python 3.12

### ISSUE THREAD

**Issue by klivolks-dev** [klivolks-dev/Nexler#107]
kafka-python 1.4.6 throwing error

Traceback (most recent call last):
  File "/app/run.py", line 10, in <module>
    from app.routes import initialize_routes
  File "/app/app/routes/__init__.py", line 2, in <module>
    from app.routes import AppsRoute, AppRoute, AppSettingsRoute, AppSecureSettingsRoute, NewAppRoute
  File "/app/app/routes/AppsRoute.py", line 2, in <module>
    from app.components import Apps
  File "/app/app/components/__init__.py", line 1, in <module>
    from .Apps import Apps
  File "/app/app/components/Apps/__init__.py", line 1, in <module>
    from app.logic.Apps import AppLogic
  File "/app/app/logic/Apps/__init__.py", line 1, in <module>
    from .AppLogic import AppLogic
  File "/app/app/logic/Apps/AppLogic.py", line 3, in <module>
    from nexler.utils.error_util import handle_http_exception
  File "/app/nexler/utils/error_util.py", line 2, in <module>
    from nexler.services.LoggerService import LoggerService
  File "/app/nexler/services/__init__.py", line 7, in <module>
    from .KafkaService import KafkaService
  File "/app/nexler/services/KafkaService.py", line 1, in <module>
    from kafka import KafkaConsumer, KafkaProducer, KafkaAdminClient
  File "/usr/local/lib/python3.12/site-packages/kafka/__init__.py", line 21, in <module>
    from kafka.admin import KafkaAdminClient
  File "/usr/local/lib/python3.12/site-packages/kafka/admin/__init__.py", line 4, in <module>
    from kafka.admin.client import KafkaAdminClient
  File "/usr/local/lib/python3.12/site-packages/kafka/admin/client.py", line 10, in <module>
    from kafka.client_async import KafkaClient, selectors
  File "/usr/local/lib/python3.12/site-packages/kafka/client_async.py", line 22, in <module>
    from kafka.cluster import ClusterMetadata
  File "/usr/local/lib/python3.12/site-packages/kafka/cluster.py", line 12, in <module>
    from kafka.conn import collect_hosts
  File "/usr/local/lib/python3.12/site-packages/kafka/conn.py", line 29, in <module>
    from kafka.protocol.admin import SaslHandShakeRequest
  File "/usr/local/lib/python3.12/site-packages/kafka/protocol/__init__.py", line 3, in <module>
    from kafka.protocol.legacy import (
  File "/usr/local/lib/python3.12/site-packages/kafka/protocol/legacy.py", line 10, in <module>
    import kafka.protocol.message
  File "/usr/local/lib/python3.12/site-packages/kafka/protocol/message.py", line 6, in <module>
    from kafka.codec import (has_gzip, has_snappy, has_lz4,
  File "/usr/local/lib/python3.12/site-packages/kafka/codec.py", line 9, in <module>
    from kafka.vendor.six.moves import range
ModuleNotFoundError: No module named 'kafka.vendor.six.moves'

**Comment by klivolks-dev** [comment]
solved with confluent_python

**Comment by klivolks-dev** [comment]
v1.4.4 solved the issue
