### ISSUE TITLE
Error in component creation

### ISSUE THREAD

**Issue by klivolks-dev** [klivolks-dev/Nexler#115]
(venv) vishnuprakash@Mac AuthService % nexler create component AuthoriseApp --url="/authorise" --namespace=app --methods=POST
An error occurred while creating the component: [Errno 2] No such file or directory: 'app/components/AuthoriseApp/__init__.py', Trace: Traceback (most recent call last):
  File "/Users/vishnuprakash/Work/icorp-v3/Services/AuthService/venv/lib/python3.12/site-packages/nexler/component/__init__.py", line 87, in create_component
    file_util.write_file(file_path, class_definition)
  File "/Users/vishnuprakash/Work/icorp-v3/Services/AuthService/venv/lib/python3.12/site-packages/nexler/utils/file_util.py", line 23, in write_file
    with open(path, 'w', encoding='utf-8') as file:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'app/components/AuthoriseApp/__init__.py'

**Comment by klivolks-dev** [comment]
issue is because incorrect Projectpath

**Comment by klivolks-dev** [comment]
Solved but require some kind of validation during project route identification
